export enum LinkRelTypes {
  alternate = "alternate",
  author = "author",
  canonical = "canonical",
  dnsprefetch = "dns-prefetch",
  help = "help",
  icon = "icon",
  license = "license",
  next = "next",
  pingback = "pingback",
  preconnect = "preconnect",
  prefetch = "prefetch",
  preload = "preload",
  prev = "prev",
  search = "search",
  stylesheet = "styleshet",
}
