/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@inspirationlabs/router';
import '@stencil/state-tunnel';
import {
  LocationSegments,
  MatchResults,
} from '@inspirationlabs/router';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface IlMenuMain {
    'data': any;
  }
  interface IlMenuMainAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }

  interface IlSection {
    'data': any;
  }
  interface IlSectionAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }

  interface SiteLoader {
    'baseDomain': string;
    'componentProps'?: { [key: string]: any };
    'location'?: LocationSegments;
    'match': MatchResults;
    'page': string;
  }
  interface SiteLoaderAttributes extends StencilHTMLAttributes {
    'baseDomain'?: string;
    'componentProps'?: { [key: string]: any };
    'location'?: LocationSegments;
    'match'?: MatchResults;
    'page'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'IlMenuMain': Components.IlMenuMain;
    'IlSection': Components.IlSection;
    'SiteLoader': Components.SiteLoader;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'il-menu-main': Components.IlMenuMainAttributes;
    'il-section': Components.IlSectionAttributes;
    'site-loader': Components.SiteLoaderAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLIlMenuMainElement extends Components.IlMenuMain, HTMLStencilElement {}
  var HTMLIlMenuMainElement: {
    prototype: HTMLIlMenuMainElement;
    new (): HTMLIlMenuMainElement;
  };

  interface HTMLIlSectionElement extends Components.IlSection, HTMLStencilElement {}
  var HTMLIlSectionElement: {
    prototype: HTMLIlSectionElement;
    new (): HTMLIlSectionElement;
  };

  interface HTMLSiteLoaderElement extends Components.SiteLoader, HTMLStencilElement {}
  var HTMLSiteLoaderElement: {
    prototype: HTMLSiteLoaderElement;
    new (): HTMLSiteLoaderElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'il-menu-main': HTMLIlMenuMainElement
    'il-section': HTMLIlSectionElement
    'site-loader': HTMLSiteLoaderElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'il-menu-main': HTMLIlMenuMainElement;
    'il-section': HTMLIlSectionElement;
    'site-loader': HTMLSiteLoaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
