name: Node CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
        npm run build -- --prerender
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: browserstack tests
      run: |
        npm install webdriverio@4.14.4 browserstack-local@1.4.0 wdio-mocha-framework@0.6.4 chai@4.2.0 wdio-static-server-service@1.0.1
        export HOST_IP="$(hostname -i | awk '{print $1}')"
        npm run browserstack
      env:
        browserstackkey: ${{ secrets.browserstackkey }}
        browserstackuser: ${{ secrets.browserstackuser }}
